version: '3'

services:
  web:
    build:
      .
    container_name: php
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./apache2:/etc/apache2/sites-available
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7.27
    container_name: mysql-server
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog
